site_name: TgIntegration Documentation
site_url: https://josxa.github.io/tgintegration
repo_url: https://github.com/JosXa/tgintegration
theme:
  name: material
  #  logo: 'assets/tgintegration-logo.png'
  favicon: 'assets/favicon.png'
  icon:
    repo: fontawesome/brands/github
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs

extra:
  generator: false  # Only for insiders
  tgi: '_tgintegration_'

extra_css:
  - styles/mkapi-overrides.css
  - styles/mkdocstrings-overrides.css

nav:
  - Docs:
      - Introduction: 'introduction.md'
      - Setup: 'setup.md'
      - Getting Started: 'getting-started.md'
  - 'API Reference': mkapi/api/tgintegration|upper
  - Doc plugin comparison:
      - Mkdocstrings reference: 'api-mkdocstrings.md'
      - Mkapi reference: 'api-mkapi.md'

markdown_extensions:
  - meta
  - markdown_include.include:
      base_path: docs
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - codehilite

plugins:
  - search
  # TODO: Decision pending between mkapi and mkdocstrings
  - mkapi:
      src_dirs: [ "tgintegration" ]
  - mkdocstrings:
      default_handler: python
      watch:
        - tgintegration
  - markdownextradata:
      data: 'extra_templates.yml'
