[tool.poetry]
name = "tgintegration"
version = "0.2.4"
description = "An Integration Test Library for Telegram Messenger Bots on top of Pyrogram."
authors = ["Joscha Goetzer <joscha.goetzer@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5.2"
pyrogram = "^0.16.0"

[tool.poetry.dev-dependencies]
bumpversion="0.5.3"
wheel="0.29.0"
watchdog="0.8.3"
flake8="2.6.0"
tox="2.3.1"
coverage="4.1"
cryptography="1.7"
PyYAML="5.1"
pytest="2.9.2"
pytest-runner="2.11.1"
sphinx = "^2.3.0"
sphinx-autodoc-typehints = "^1.10.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
