name: Docs
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: "Install Poetry"
        uses: Gr1N/setup-poetry@v3
        with:
          poetry-version: 1.0
      - name: Poetry install
        run: poetry install
      - run: poetry run mkdocs gh-deploy --force
