name: Test Telegram Notifications

on:
  workflow_dispatch:


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Send message to @TgIntegration
        uses: appleboy/telegram-action@master
        with:
          to: '@TgIntegration'
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed.
